# Permalinks
permalink:        pretty

# Setup
title:            Disaster Damage Detection
tagline:          ''
description:      'Automatic damage detection in satellite imagery after hurricanes'
url:              "https://dds-lab.github.io"
baseurl:          "/disaster-damage-detection"

# Custom vars
version:          2.1.0
