# Permalinks
permalink:        pretty

# Setup
title:            Disaster Damage Detection
tagline:          ''
description:      'A Data Science for Social Good 2018 fellowship project'
url:              "https://dds-lab.github.io"
baseurl:          "/disaster-damage-detection"

# Custom vars
version:          2.1.0
